services:
  rss-tracker:
    image: ikeapencill/rss-tracker:latest
    container_name: rss-keyword-tracker
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
